driver: ptp_clock: Fix PTP_CLOCK_INIT macro
There is a conflict of the argument with the field it initializes which
causes the following error if the name of the variable used as the
argument is different than the structs field:

  ptp_clock.h:67:3: error: unknown field ‘XX’ specified in initializer
    .api = &(api),
  ptp_clock.h:73:2: note: in expansion of macro ‘PTP_CLOCK_INIT’
    PTP_CLOCK_INIT(dev_name, 0, api)

Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>